#!/bin/bash

if [ $# -ne 2 ]
then
 echo "Debe ingresar 2 parametros"
 exit 1
fi


select opcion in suma resta prod div exit
do
case $opcion in
"suma")
echo "suma: $(expr $1 + $2)"
;;
"resta")
echo "resta: $(expr $1 - $2)"
;;
"prod")
echo "multiplicacion: $(expr $1 \* $2)"
;;
"div")
echo "division: $(expr $1 / $2)"
;;
*)
echo "adios"
exit 0
esac
done

