#!/bin/bash

if [ $# -ne 2 ]
then
 echo "Debe ingresar 2 parametros"
 exit 1
fi

echo "multiplicacion: $(expr $1 \* $2)"
echo "suma: $(expr $1 + $2)"
echo "resta: $(expr $1 - $2)"
if [ $1 -gt $2 ]
then
mayor=$1
else
mayor=$2
fi
echo "mayor: $mayor"

