#!/bin/bash

select opcion in Listar DondeEstoy QuienEsta
do
case $opcion in
"Listar")
ls
;;
"DondeEstoy")
echo "Usted se encuentra en: $(pwd)"
;;
"QuienEsta")
who
;;
*)
echo "adios"
exit 0
;;
esac
done
