#!/bin/bash

if [ $# -ne 0 ]
then
  echo "No se permiten parametros"
  exit 1
fi

num=(1 2 3 4 5 6 7 8 9 10)
count=0
for element in ${num[@]}
do
  if [ $(expr $element % 2) -eq 0 ]
  then
    echo $element
  else
    count=$(expr $count + 1)
  fi
done

echo "Cantidad de impares: $count"

