#!/bin/bash
#Crear un script que presente un menu al usuario con las siguiente opciones:
#a- Inicializaar vector: inicializar el vector con numero del 1 al 10
#b- Longitud del vector: imprime la cantidad de elementos del vector
#c- Elementos: imprime todos los elementos del vector


vector=()

function iniciar{
#otras formas de hacerlo
#vector=({1..10})
#vector=(1 2 3 4 5 6 7 8 9 10)

 vector=$(seq 1 10) 

 echo "iniciado"
}


longitud(){
 echo la longitud es: ${#vector[@]}
}

elementos(){
 echo los elementos son: ${vector[@]}
}

select option in iniciar longitud elementos exit; do
 $option
done


